-- Add Step 2 columns to employment_applications table
-- 17 rating fields (integer 1-5) and 18 open text answer fields

ALTER TABLE employment_applications
  ADD COLUMN IF NOT EXISTS r1 int,
  ADD COLUMN IF NOT EXISTS r2 int,
  ADD COLUMN IF NOT EXISTS r3 int,
  ADD COLUMN IF NOT EXISTS r4 int,
  ADD COLUMN IF NOT EXISTS r5 int,
  ADD COLUMN IF NOT EXISTS r6 int,
  ADD COLUMN IF NOT EXISTS r7 int,
  ADD COLUMN IF NOT EXISTS r8 int,
  ADD COLUMN IF NOT EXISTS r9 int,
  ADD COLUMN IF NOT EXISTS r10 int,
  ADD COLUMN IF NOT EXISTS r11 int,
  ADD COLUMN IF NOT EXISTS r12 int,
  ADD COLUMN IF NOT EXISTS r13 int,
  ADD COLUMN IF NOT EXISTS r14 int,
  ADD COLUMN IF NOT EXISTS r15 int,
  ADD COLUMN IF NOT EXISTS r16 int,
  ADD COLUMN IF NOT EXISTS r17 int;

ALTER TABLE employment_applications
  ADD COLUMN IF NOT EXISTS a1 text,
  ADD COLUMN IF NOT EXISTS a2 text,
  ADD COLUMN IF NOT EXISTS a3 text,
  ADD COLUMN IF NOT EXISTS a4 text,
  ADD COLUMN IF NOT EXISTS a5 text,
  ADD COLUMN IF NOT EXISTS a6 text,
  ADD COLUMN IF NOT EXISTS a7 text,
  ADD COLUMN IF NOT EXISTS a8 text,
  ADD COLUMN IF NOT EXISTS a9 text,
  ADD COLUMN IF NOT EXISTS a10 text,
  ADD COLUMN IF NOT EXISTS a11 text,
  ADD COLUMN IF NOT EXISTS a12 text,
  ADD COLUMN IF NOT EXISTS a13 text,
  ADD COLUMN IF NOT EXISTS a14 text,
  ADD COLUMN IF NOT EXISTS a15 text,
  ADD COLUMN IF NOT EXISTS a16 text,
  ADD COLUMN IF NOT EXISTS a17 text,
  ADD COLUMN IF NOT EXISTS a18 text;

ALTER TABLE employment_applications
  ADD COLUMN IF NOT EXISTS step int DEFAULT 1;
